name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_curiosity:
    path: ../
  fl_extended: ^1.6.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
