name: flutter_curiosity
description: The flutter curiosity is compatible with android and ios for multiple native features
version: 6.1.0
repository: https://github.com/Wayaer/flutter_curiosity.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: flutter.curiosity
        pluginClass: CuriosityPlugin
      ios:
        pluginClass: CuriosityPlugin
      macos:
        pluginClass: CuriosityPlugin


